services:
  # --- Base de Datos (Postgres + Timescale) ---
  db:
    image: timescale/timescaledb-ha:pg16
    container_name: wealthroad-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: securepassword123
      POSTGRES_DB: wealthroad
    volumes:
      - wealthroad_postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - wealth-net

  # --- Backend (FastAPI) ---
  backend:
    build: ./backend
    container_name: wealthroad-api
    restart: always
    ports:
      - "8000:8000"
    environment:
      # Conexión a la DB usando el nombre del servicio 'db'
      DATABASE_URL: postgresql://admin:securepassword123@db:5432/wealthroad
    depends_on:
      - db
    volumes:
      - ./backend:/app # Hot-reload: cambios en código se ven al instante
    networks:
      - wealth-net

  # --- Frontend (React) ---
  frontend:
    build: ./frontend
    container_name: wealthroad-ui
    restart: always
    ports:
      - "8080:8080" # O el puerto que use tu React
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita sobrescribir librerías locales
    networks:
      - wealth-net


volumes:
  wealthroad_postgres_data:

# --- Red Privada ---
networks:
  wealth-net:
    driver: bridge
