services:
  # --- Base de Datos (TimescaleDB) ---
  db:
    image: timescale/timescaledb:latest-pg16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - wealthroad_postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
      - ./database/migrations:/docker-entrypoint-initdb.d/migrations
    networks:
      - wealth-net

  # --- Backend (FastAPI) ---
  backend:
    build: ./backend
    restart: always
    expose:
      - "8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      AIS_USER: ${AIS_USER}
      AIS_PASS: ${AIS_PASS}
      # --- CONEXIÓN IBKR ---
      IBKR_GATEWAY_HOST: ib-gateway-ib-gateway-1  # <--- Nombre del contenedor vecino
      IBKR_GATEWAY_PORT: 4003                     # <--- Puerto interno (Live)
      IBKR_CLIENT_ID: 100
      IBKR_MARKET_DATA_TYPE: 1
    depends_on:
      - db
    networks:
      - wealth-net
      - ib-net           # <--- AÑADE ESTA LÍNEA (la definiremos abajo)
  # --- Servidor Web (Caddy) ---
  caddy:
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - wealth-net

volumes:
  wealthroad_postgres_data:
  caddy_data:
  caddy_config:

networks:
  wealth-net:
    driver: bridge
  
  ib-net:                # <--- AÑADE ESTO
    external: true       # <--- Dice que es una red que YA existe fuera
    name: ib-gateway_default  # <--- El nombre que acabamos de encontrar